version: '3.5'

services:
  database1:
    image: postgres:10
    volumes:
      - database1_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database1.env
    networks:
      - net

  web:
    image: gabrielv/avizier-virtual:local
    environment:
      - DJANGO_SETTINGS_MODULE=website.settings
      - DJANGO_DEBUG=on
    volumes:
      - ./web:/web
      - ./volumes/static:/static
      - media:/media
    env_file:
      - config/db/database1.env
    networks:
      - net
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./volumes/static:/opt/services/djangoapp/static:ro
      - media:/opt/services/djangoapp/media:ro
    networks:
      - net
    depends_on:
      - web

networks:
  net:
    driver: overlay

volumes:
  database1_volume:
  media:
