defaultEntryPoints = ["http"]
logLevel = "INFO"

[traefikLog]
filePath = "/dev/stdout"

[accessLog]
filePath = "/dev/stdout"

[api]
readOnly = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

[docker]
swarmMode = true
watch = true
domain = "docker"
network = "traefik_network"
